  name: build-and-release-deb
  on:
    push:
      tags:
        - 'v*'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install fpm
          run: |
            sudo apt-get update
            sudo apt-get install -y ruby ruby-dev build-essential
            sudo gem install --no-document fpm
        - name: Make script executable
          run: |
            chmod +x capty
        - name: Build .deb
          run: |
            VERSION=${GITHUB_REF_NAME#v}
            fpm -s dir -t deb -n capty -v "$VERSION" \
              --depends "python3" \
              --depends "python3-gi" \
              --depends "gir1.2-gtk-3.0" \
              --depends "ffmpeg" \
              --depends "slop" \
              --depends "gifsicle" \
              ./capty=/usr/local/bin/capty \
              ./capty.desktop=/usr/share/applications/capty.desktop
              ./icon.png=/usr/share/pixmaps/capty.png
            mv capty_*_amd64.deb capty_${VERSION}_amd64.deb
        - name: Upload to Release
          uses: softprops/action-gh-release@v2
          with:
            files: capty_*_amd64.deb
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}