  name: build-and-release-deb
  on:
    push:
      tags:
        - 'v*'
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install fpm
          run: |
            sudo apt-get update
            sudo apt-get install -y ruby ruby-dev build-essential
            sudo gem install --no-document fpm
        - name: Make script executable
          run: |
            chmod +x capty.py
        - name: Build .deb
          run: |
            VERSION=${GITHUB_REF_NAME#v}
            fpm -s dir -t deb -n capty -v "$VERSION" \
              --depends "python3" \
              --depends "python3-gi" \
              --depends "gir1.2-gtk-3.0" \
              --depends "ffmpeg" \
              --depends "slop" \
              --depends "gifsicle" \
              --maintainer "rawallon@wallon" \
              --description "Capty is a simple area screen recorder for Linux that lets you quickly record a selected screen area to MP4 or GIF. It provides a tiny GTK window to pick a region, set a delay, choose FPS and format, then start/stop recording. Features include area selection, MP4/GIF output, FPS control, delayed start, overlay, and hotkey support." \
              --url "https://github.com/Rawallon/capty" \
              --category "Utility" \
              --license "CC-BY-NC-4.0" \
              --vendor "rawallon" \
              ./capty.py=/usr/local/bin/capty \
              ./capty.desktop=/usr/share/applications/capty.desktop \
              ./icon.png=/usr/share/pixmaps/capty.png
            # List the created package
            ls -la capty_*_amd64.deb
        - name: Upload to Release
          uses: softprops/action-gh-release@v2
          with:
            files: capty_*_amd64.deb
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}